sudo: false
language: node_js
node_js:
  - "8"

cache:
  directories:
    - node_modules

script:
  - cd frontend
  - yarn install
  - yarn build

deploy:
  on:
    branch: dev-bootstrap-frontend
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_ACCESS_KEY_SECRET
  bucket: "pina-colada"
  local_dir: dist
  skip_cleanup: true
